"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import api from "@/lib/api";
import { useAuth } from "@/lib/useAuth";

type QAItem = {
  question: string;
  answer: string;
};

export default function AskDocumentClient() {
  const { id: documentId } = useParams<{ id: string }>();
  const { user, loading: authLoading } = useAuth();

  const [documentName, setDocumentName] = useState("Document");
  const [question, setQuestion] = useState("");
  const [answers, setAnswers] = useState<QAItem[]>([]);
  const [loading, setLoading] = useState(false);

  /* ---------- AUTH GUARD ---------- */
  if (authLoading) {
    return <p className="text-textSecondary">Loading session…</p>;
  }

  if (!user) {
    return <p>Please sign in to ask questions.</p>;
  }

  /* ---------- LOAD DOCUMENT NAME ---------- */
  useEffect(() => {
    if (authLoading || !user || !documentId) return;

    api.get("/documents").then((res) => {
      if (Array.isArray(res.data)) {
        const doc = res.data.find((d: any) => d.id === documentId);
        if (doc) setDocumentName(doc.file_name);
      }
    });
  }, [authLoading, user, documentId]);

  /* ---------- ASK HANDLER ---------- */
  const handleAsk = async () => {
    if (!question.trim() || !user) return;

    setLoading(true);

    try {
      const res = await api.post("/ask", {
        document_id: documentId,
        question,
      });

      const answerText =
        res.data?.answer ??
        res.data?.context?.join("\n\n") ??
        "No answer found.";

      setAnswers((prev) => [
        ...prev,
        { question, answer: answerText },
      ]);

      setQuestion("");
    } catch (err) {
      alert("Failed to get answer.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <section className="max-w-4xl mx-auto space-y-8">
      {/* ---------- Header ---------- */}
      <header className="space-y-1">
        <h1 className="text-3xl font-semibold">{documentName}</h1>
        <p className="text-sm text-textSecondary">
          Ask questions grounded in this document’s content.
        </p>
      </header>

      {/* ---------- Ask Input ---------- */}
      <div className="border rounded-xl p-6 bg-white space-y-4">
        <textarea
          className="w-full border rounded-md p-3 resize-none"
          rows={4}
          placeholder="Ask a question about this document..."
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
        />

        <div className="flex justify-end">
          <button
            onClick={handleAsk}
            disabled={loading || !question.trim()}
            className="px-4 py-2 text-sm border rounded-md hover:bg-gray-50 disabled:opacity-50"
          >
            {loading ? "Thinking…" : "Ask"}
          </button>
        </div>
      </div>

      {/* ---------- Answers ---------- */}
      {answers.length > 0 && (
        <div className="space-y-6">
          <h2 className="text-xl font-medium">Answers</h2>

          {answers.map((item, idx) => (
            <div
              key={idx}
              className="border rounded-xl p-6 bg-white space-y-2"
            >
              <p className="font-medium">Q: {item.question}</p>
              <p className="text-textSecondary whitespace-pre-wrap">
                {item.answer}
              </p>
            </div>
          ))}
        </div>
      )}

      {/* ---------- Footer ---------- */}
      <p className="text-sm text-textSecondary border-t pt-4">
        Answers are generated by retrieving relevant sections from the document.
      </p>
    </section>
  );
}